apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cloud-run-dev
namePrefix: dev-
resources:
- ../../base
patches:
- path: patch-spec.yaml
  target:
    group: serving.knative.dev
    version: v1
    kind: Service
    name: streamlit-cr-demo

  