apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: streamlit-cr-demo
  annotations:
    run.googleapis.com/ingress: all 
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/sessionAffinity: 'true'
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 3000
      serviceAccountName: streamlit-sa@ts24-dev-sandbox.iam.gserviceaccount.com
      containers:
      - image: streamlit-cr-demo
        resources:
          limits:
            cpu: '1'
            memory: 256Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080



   